### ISSUE TITLE
compresshandler doesn't work with response code

### ISSUE THREAD

**Issue by azhao12345** [gorilla/handlers#102]
This sends the status code, but doesn't return any body
```
w.WriteHeader(http.StatusNotFound)
err := myTemplate.ExecuteTemplate(w, whatever)
```

**Comment by elithrar** [comment]
What error, if any, is returned? Can you provide a minimal, verifiable example?

**Comment by azhao12345** [comment]
Instead of page content, we get a completely blank response body.

The minimum viable example would be to call WriteHeader, then write any data to the writer afterwards.

**Comment by azhao12345** [comment]
The response code is set correctly though, it's just the body is empty
