### ISSUE TITLE
Set up CORS on Subrouter 

### ISSUE THREAD

**Issue by koalalorenzo** [gorilla/handlers#115]
I am facing some problems setting up the CORS handler when using a sub router, The specific needs is that I would like to set up the handler to answer specific paths, but that implies that I use `mux.Router.Methods()` and `mux.Router.Path()`. How can I use `handlers.CORS` properly? 

This is the code that is not providing an answer when using `OPTIONS` as method:

```golang
func setRoutes(mr *mux.Router) {
	s := mr.PathPrefix("/objects").Subrouter()

	headersOk := handlers.AllowedHeaders([]string{"*"})
  originsOk := handlers.AllowedOrigins([]string{"*"})
  methodsOk := handlers.AllowedMethods([]string{"GET", "POST", "DELETE"})
	CORSCheck := handlers.CORS(headersOk, originsOk, methodsOk)

	baseMiddlewares := alice.New(CORSCheck, Auth.HTTPMiddleware)

	listCombo := baseMiddlewares.Then(http.HandlerFunc(listObj))
	s.Methods("GET", "OPTIONS").Path("/").Handler(listCombo)

	createCombo := baseMiddlewares.Then(http.HandlerFunc(createObj))
	s.Methods("POST").Path("/").Handler(createCombo)

	deleteCombo := baseMiddlewares.Then(http.HandlerFunc(deleteObj))
	s.Methods("DELETE", "OPTIONS").Path("/:uuid").Handler(deleteCombo)
}
```

I have even tried to set up a single path like that:

```golang
s.Methods("OPTIONS").Path("/").Handler(CORSCheck(emptyAnswerHandler))
```

Any suggestion? Am I forced to set up CORS on the very first set up of the http server?

**Comment by koalalorenzo** [comment]
When I am testing this, I always get a `403`

```bash
$ curl 'http://127.0.0.1:18080/objects/' -D - \
-XOPTIONS \
-H 'Referer: http://127.0.0.1:8080/' \
-H 'Access-Control-Request-Headers: authorization' \
-H 'Origin: http://127.0.0.1:8080' \
-H 'Accept: */*' \
-H 'Access-Control-Request-Method: GET'
```
I get:
```
HTTP/1.1 403 Forbidden
Date: Sun, 22 Oct 2017 10:01:46 GMT
Content-Length: 0
Content-Type: text/plain; charset=utf-8
```

What am I doing wrong?

**Comment by elithrar** [comment]
It looks like the 403 is returned from your auth middleware; can you
confirm? I see no CORS headers in the response.

**Comment by koalalorenzo** [comment]
Yes Ideally that should come from the 403, but I was also expecting the headers from the CORS.
What am I doing wrong?

**Comment by koalalorenzo** [comment]
I have actually re-wrote the middleware as it was broken, disabled it and now if I call directly `GET` it works... bu the `OPTIONS` are still returning a `403`. Should I anyway handle them in the Subrouter?

**Comment by champtar** [comment]
Just got the same issue, and I did:
```
s.Methods("OPTIONS")
s.Use(CORSCheck)
```
