### ISSUE TITLE
breaking change with returned Access-Control-Allow-Origin header

### ISSUE THREAD

**Issue by cainlevy** [gorilla/handlers#117]
Prior to https://github.com/gorilla/handlers/pull/116, specifying `AllowedOriginValidator` acted as an override to `AllowedOrigins`. Afterwards, the same configuration will return `Access-Control-Allow-Origin: *` because of the default value for `allowedOrigins`.

```
// before: will only reflect allowed origins
// after: will reflect "*"
gorilla.CORS(
  gorilla.AllowedOriginValidator(myValidator)
)
```

Fixing this requires specifying a blank `AllowedOrigins` to override the default value:

```
gorilla.CORS(
  gorilla.AllowedOrigins([]string{})
  gorilla.AllowedOriginValidator(myValidator)
)
```

**Comment by cainlevy** [comment]
I think the difference between gorilla/handlers and the other examples listed in #116 is that gorilla/handlers treated `AllowedOriginValidator` as an override and _ignored_ the default `*` configuration.

It should be possible to specify `AllowedOriginValidator(myValidator)` alongside `AllowCredentials()`. It should _not_ be possible to specify `AllowedOrigins([]string{"*"})` alongside `AllowCredentials()`.

**Comment by faryon93** [comment]
+1

**Comment by kisielk** [comment]
@elithrar thoughts on this one? It's been a while since I've looked at CORS details

**Comment by elithrar** [comment]
Let me take a look this weekend & assess.
