### ISSUE TITLE
Disallowing GET through CORS doesn't work

### ISSUE THREAD

**Issue by karel-3d** [gorilla/handlers#119]
I am trying to disallow GET request through CORS headers. But it doesn't seem to work.

This is the code.

```go
package main

import (
        "encoding/json"
        "net/http"

        "github.com/gorilla/handlers"
        "github.com/gorilla/mux"
)

func main() {
        https := &http.Server{
                Addr: ":8080",
        }

        r := mux.NewRouter()

        r.HandleFunc("/", hello)

        methods := handlers.AllowedMethods([]string{"HEAD", "POST", "OPTIONS"})

        https.Handler = handlers.CORS(methods)(r)

        https.ListenAndServe()
}

func hello(w http.ResponseWriter, r *http.Request) {
        json.NewEncoder(w).Encode("hello!")
}
```

This still works, even when GET is not in the allowed methods

`(await fetch("http://127.0.0.1:8080")).json()` => `hello!`

**Comment by elithrar** [comment]
If you are testing from localhost to localhost, you won’t be making a
cross-origin request.

Can you share the request & response headers of your XHR (fetch) call?
