### ISSUE TITLE
Logging to multiple files. Is it possible?

### ISSUE THREAD

**Issue by sttyru** [gorilla/handlers#123]
Hello!

**Thanks for awesome library!** I use `gorilla/handler` (especially `LoggingHandler`) with `Goji` and have fun :)
My question: can I write logs to multiple files? I want to implement yet another tool for simulate of 'bad HTTP-backends' and I need to sort logs by files based on some parameters (e.g. 'listen port' of instance). I want get multiple little files instead the one huge monster :)
Now my code looks like:
```      
         f, err := logInit(cnf.Acc_log)
         if err != nil {
             excl := &EError{Content: err.Error(), Retcode: 4}
             excl.ee()
         }
         defer f.Close()
         r.Use(handlers.ProxyHeaders)
         lr := handlers.LoggingHandler(f, r)
         // -- Endless
         srv := endless.NewServer(cnf.Port, lr)
```
Is it possible to transform this code to the solution for processing of multiple files? Or I should find an another way?

**Thanks for advice!**

**Comment by elithrar** [comment]
You probably want to do this out of process, either in a tool that can
aggregate logs for you - ElasticSearch, BigQuery, etc - or a tool that
reads stdout from your process and processes logs.

Else, you won’t be able to write to the same file from multiple goroutines,
so you likely want to push some kind of Log type down a channel to a
consumer that sorts & processes them.

**Comment by elithrar** [comment]
(Closing, as ultimately outside the scope of this library, but follow up questions are welcome)

**Comment by sttyru** [comment]
Thanks! I did not thinks about of 'external tools'... It's a great idea ))
