### ISSUE TITLE
username field in LoggingHandler

### ISSUE THREAD

**Issue by tokenrain** [gorilla/handlers#125]
I had opened Pull Request #124 to allow for a non standard header to set the username in the CLF if the username set in the URL was blank. I totally get that you do not want to support a non standard header. I am trying to avoid re writing this library (which is great and does 99.9% of what I need) just to get the that field set since I can not use the URL based username with the way that we perform authentication. I was just wondering if I placed another request that used the standard From header in place of X-Remote-User if you would accept that. If not do you know a way to set the Userinfo struct manually. I can not figure that out. Thanks

**Comment by elithrar** [comment]
You can just inject the username into the `url.UserInfo` struct directly by writing some middleware that runs prior to `LoggingHandler` - e.g.

```
func extractUserMiddleware(next http.Handler) http.Handler {
        fn := func(w http.ResponseWriter, r *http.Request) {
                // Extract the user from the session, header, etc.
                r.URL.User = url.User(r.Header.Get("X-Remote-User"))

                next.ServeHTTP(w, r)
        }
}
```

```
// Where 'r' is your router instance
        loggedRouter := extractUserMiddleware(handlers.LoggingHandler(os.Stdout, r))
        srv := &http.Server{
                Addr: ":" + port,
                // Good practice to set timeouts to avoid Slowloris attacks.
                WriteTimeout: time.Second * 15,
                ReadTimeout:  time.Second * 15,
                IdleTimeout:  time.Second * 60,
                Handler:      loggedRouter,
        }
```
```
# No user supplied
➜ penguin ~/repos/scratch  curl localhost:8080/
Hello! 👋
# Output
# ::1 - - [27/Jun/2018:16:45:01 +0000] "GET / HTTP/1.1" 200 12

# User in header
➜ penguin ~/repos/scratch  curl localhost:8080/ -H "X-Remote-User: @elithrar"
Hello! 👋
# Output
# ::1 - @elithrar [27/Jun/2018:16:45:14 +0000] "GET / HTTP/1.1" 200 12
```

This makes it innately flexible and doesn't require this library to bake anything in.
