### ISSUE TITLE
Support for custom log formatters

### ISSUE THREAD

**Issue by mlsquires** [gorilla/handlers#130]
The package currently has two log formatters, along with the mechanisms to support them. If someone wants to have another formatter they need to add their code into the package (either here or in a fork).

I think it would be great to have a way for people to use the package and supply their own formatters. I've added support for custom log formatter here:
https://github.com/mlsquires/handlers/blob/feature/customloggers/handlers.go

Would you like a pull request?

**Comment by kisielk** [comment]
I think it's a good idea. Could be used to implement #129 more properly as well.

One thing I would change is the `LogFormatter` to accept a writer and then a struct with all the log info. That way it's less messy and also future proof.

**Comment by Daniel-B-Smith** [comment]
This is indeed a better option than #129. My one suggestion would be to make the existing `writeLog` method public as well. That way, clients can scrub the request without having to reimplement all of the formatting provided by `writeLog`.

**Comment by kisielk** [comment]
I thought about that, but you can always just copy it out of the source code.

**Comment by mlsquires** [comment]
I think having the two log formatters that are already in the package there as directly useful for a bunch of people and as examples is a good thing. By adding the ability to register a formatter then people can do whatever they need to outside the package while leveraging all the mechanisms. If you need a url scrubbing formatter you can just grab one of the existing formatters, modify it in your application code, register it, and you have what you need.

There is a tradeoff between having everything in a package be hard-wired and providing options/pluggable components for every possible thing. I obviously think that providing the formatter as a pluggable component is good. But I'm not sure that we should go further in providing options/pluggables.

I'll generate a pull request and we can talk about the specifics there.

**Comment by mlsquires** [comment]
Since this adds a new feature but retains full backward compatibility, should this get some sort of version bump? It is currently v1.3.0 (without this addition). For my usage, I'd like to reference a version that has this stuff in it.

**Comment by elithrar** [comment]
Sure. We usually review API status every now-and-then to bump (no formal schedule). I can make a release by the end of the weekend.

**Comment by elithrar** [comment]
@mlsquires Done! https://github.com/gorilla/handlers/releases/tag/v1.4.0

**Comment by elithrar** [comment]
(And thanks for your contributions!)
