### ISSUE TITLE
Compress handler support of http.Pusher interface

### ISSUE THREAD

**Issue by inliquid** [gorilla/handlers#137]
Does current implementation support Pusher interface, or is it planned?

**Comment by elithrar** [comment]
Nothing planned. Happy to accept PRs, but as this has been idle for a while
I wanted to clean it up.

There’s been minimal asks for this to date.

**Comment by inliquid** [comment]
Being fixed by https://github.com/gorilla/handlers/pull/138

**Comment by inliquid** [comment]
Hm... just realized that it probably redundant. Will have some more tests...

**Comment by inliquid** [comment]
Yep, everything's fine.
