### ISSUE TITLE
CORS middleware doesn't work with mux.Router.Use()

### ISSUE THREAD

**Issue by aidansteele** [gorilla/handlers#142]
[`func (r *Router) Use(mwf ...MiddlewareFunc)`](http://www.gorillatoolkit.org/pkg/mux#Router.Use) doesn't appear to play nicely with the CORS middleware in this package. Either that or my understanding of how it should be used is incorrect and perhaps the docs could be updated. Here's a test to describe what I see:

```golang
package main

import (
	"github.com/gorilla/handlers"
	"github.com/gorilla/mux"
	"net/http"
	"net/http/httptest"
	"testing"
)

func TestCorsNotWorking(t *testing.T) {
	router, cors := routerAndCors()
	router.Use(cors) // this usage doesn't work

	if !got200(router) {
		t.Fail()
	}
}

func TestCorsWorking(t *testing.T) {
	router, cors := routerAndCors()
	corsRouter := cors(router) // this works fine

	if !got200(corsRouter) {
		t.Fail()
	}
}

func routerAndCors() (*mux.Router, mux.MiddlewareFunc) {
	router := mux.NewRouter()
	router.Path("/ping").HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(200)
	})

	cors := handlers.CORS(
		handlers.AllowedHeaders([]string{"content-type"}),
		handlers.AllowedOrigins([]string{"*"}),
		handlers.AllowCredentials(),
	)

	return router, cors
}

func got200(h http.Handler) bool {
	ts := httptest.NewServer(h)
	client := &http.Client{}

	req, _ := http.NewRequest("OPTIONS", ts.URL, nil)
	req.Header.Set("Origin", "localhost:3000")
	req.Header.Set("Access-Control-Request-Method", "GET")
	resp, _ := client.Do(req)

	return resp.StatusCode == 200
}
```

**Comment by elithrar** [comment]
Can you share what build of mux you're using?

**Comment by aidansteele** [comment]
Thanks for the speedy response. This is using v1.6.2 of `github.com/gorilla/mux`. 

After your question, I looked at the list of most recent builds and saw this in the release notes for v1.6.1:

> gorilla/mux now provides first-class support for "middleware" thanks to @roobre! Middleware are handlers that can intercept request & response processing _after a route match_

Which in turn got me to re-read [the docs](https://github.com/gorilla/mux#middleware) and notice this line:

> Mux supports the addition of middlewares to a Router, which are executed in the order they are added if a match is found, including its subrouters.

My mistake was not reading the README sufficiently before diving into the docs for the individual methods. I can now see that it's actually more than adequately documented that middlewares only execute in case of a match.

**Comment by aidansteele** [comment]
The original question was actually meant to be a minimal reproduction of my own problem, but after reading the docs I want to share the mistake I made and get your opinion on whether it was user error or something that could change in Gorilla. 

Here's another example:

```golang
package main

import (
	"github.com/gorilla/handlers"
	"github.com/gorilla/mux"
	"net/http"
	"net/http/httptest"
	"testing"
)

func TestCorsUnexpectedBehaviour(t *testing.T) {
	router := mux.NewRouter()
	router.Path("/ping").Methods("GET", "POST").HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(200)
	})

	cors := handlers.CORS(
		handlers.AllowedHeaders([]string{"content-type"}),
		handlers.AllowedOrigins([]string{"*"}),
		handlers.AllowCredentials(),
	)

	router.Use(cors)

	ts := httptest.NewServer(router)
	client := &http.Client{}

	req, _ := http.NewRequest("OPTIONS", ts.URL + "/ping", nil)
	req.Header.Set("Origin", "localhost:3000")
	req.Header.Set("Access-Control-Request-Method", "GET")
	resp, _ := client.Do(req)

	if resp.StatusCode != 200 {
		t.Fatalf("Expected 200 but got %d", resp.StatusCode)
	}
}
```

The `handlers.CORS` middleware is never firing (because the router found no match for `OPTIONS /ping`), so the client gets a 405 when I would have hoped for a 200 with the appropriate CORS response headers. I **now** understand the behaviour, but is this intuitive for new users?

I see that v1.6.2 of mux added `router.Use(mux.CORSMethodMiddleware)`, but unfortunately that doesn't work for me as I need to add the additional options seen above.

**Comment by aidansteele** [comment]
Yep, that works for me 👍 Thanks!
