### ISSUE TITLE
Would you be interested in a Brotli PR?

### ISSUE THREAD

**Issue by kamermans** [gorilla/handlers#143]
Hi, thanks for the great library!  I'm using your `compress` middleware for a project and I really need Brotli support.  Brotli is a compression algorithm that significantly outperforms gzip/deflate and is supported by the vast majority of users.  The downside is that the current stable Go libraries all use the C brotli library, so it will be unavailable for unsupported servers.  My thinking is to add another handler if the C library is available, but I need to do a bit more research on the brotli Golang landscape first.

Would you be open to pulling a PR that introduces brotli compression support?

**Comment by elithrar** [comment]
Open to a PR, although important that the C bindings are optional for users
who don’t have them / need Brotli.

**Comment by kamermans** [comment]
Thanks, and definitely, the support for Brotli would need to be explicitly enabled by the user or implicitly enabled via detection.
