### ISSUE TITLE
Are you making the opposite condition test before set header of `Access-Control-Allow-Methods`

### ISSUE THREAD

**Issue by wonderbeyond** [gorilla/handlers#145]
Are you making the opposite condition test before set header of `Access-Control-Allow-Methods`?

https://github.com/gorilla/handlers/blob/master/cors.go#L101

```go
		if !ch.isMatch(method, defaultCorsMethods) {
			w.Header().Set(corsAllowMethodsHeader, method)
		}
```

Which I think should be:

```go
		if ch.isMatch(method, defaultCorsMethods) {
			w.Header().Set(corsAllowMethodsHeader, method)
		}
```

Reference: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by Sapphire64** [comment]
Hi @wonderbeyond, this is actually correct, see here: https://fetch.spec.whatwg.org
```
If request’s method is not in methods, request’s method is not a CORS-safelisted method, and request’s credentials mode is "include" or methods does not contain `*`, then return a network error.
```
So server could either not reply with any headers, or must reply with not safelisted headers if they are requested.

**Comment by wonderbeyond** [comment]
@Sapphire64 I've checked the code logic again.

1. At [Line 101](https://github.com/gorilla/handlers/blob/master/cors.go#L101):
    I can't understand why you send an `Access-Control-Allow-Methods` header with a value of
    mismatched target method attached with the `Access-Control-Request-Method` request header.

2. I just found that if the test condition at L#101 evaluate to be true, and we don't have custom `allowedMethods`, we can't get into L#101 at all. we'll be denied at L#74.

3. With `POST` set in `allowedMethods`, an `OPTIONS` preflight request with a header `Access-Control-Request-Method: POST` just won't receive a response with header: `Access-Control-Allow-Methods: POST`.
```go
	CORS := handlers.CORS(
		handlers.AllowedOrigins([]string{"*"}),
		handlers.AllowedHeaders([]string{"Authorization"}),
		handlers.AllowedMethods([]string{"GET", "POST"}),
	)
```

---

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Preflighted_requests

![image](https://user-images.githubusercontent.com/228361/53937055-e8914100-40e6-11e9-93ad-cd07ed5857d6.png)

**Comment by wonderbeyond** [comment]
@Sapphire64 I've made change propose.

**Comment by Sapphire64** [comment]
@wonderbeyond first thing, I'm not the author of this repo and never contributed to it. But I had the same question as you.

Second thing, the behaviour you described is correct if you see the doc I sent. Also it does work in the browsers, otherwise this would have been fixed in the last 3 years since it was written :) 

Sending back "Access-Control-Allow-Methods": "POST" is optional, but if you do "DELETE" or other request then it is mandatory.

```
defaultCorsMethods          = []string{"GET", "HEAD", "POST"}
```
Please note that you don't override defaults when you pass allowed methods into the function.

So again, the scenarios:
```
OPTIONS /resources/post-here/ HTTP/1.1
Origin: http://foo.example
Access-Control-Request-Method: POST
Access-Control-Request-Headers: X-PINGOTHER, Content-Type

HTTP/1.1 200 OK
Access-Control-Allow-Origin: http://foo.example
Access-Control-Allow-Headers: X-PINGOTHER, Content-Type
Access-Control-Max-Age: 86400
```
Good.

```
OPTIONS /resources/post-here/ HTTP/1.1
Origin: http://foo.example
Access-Control-Request-Method: DELETE
Access-Control-Request-Headers: X-PINGOTHER, Content-Type

HTTP/1.1 200 OK
Access-Control-Allow-Origin: http://foo.example
Access-Control-Allow-Headers: X-PINGOTHER, Content-Type
Access-Control-Max-Age: 86400
```
Bad.

```
OPTIONS /resources/post-here/ HTTP/1.1
Origin: http://foo.example
Access-Control-Request-Method: DELETE
Access-Control-Request-Headers: X-PINGOTHER, Content-Type

HTTP/1.1 200 OK
Access-Control-Allow-Origin: http://foo.example
Access-Control-Allow-Methods: DELETE
Access-Control-Allow-Headers: X-PINGOTHER, Content-Type
Access-Control-Max-Age: 86400
```
Good.

https://fetch.spec.whatwg.org/ - this page explains it in deep, and Mozilla has references to it.
