### ISSUE TITLE
CompressHandler gzip's twice

### ISSUE THREAD

**Issue by klingtnet** [gorilla/handlers#153]
The `CompressHandler` of [gorilla/handlers][1] gzips responses twice if they're already gzipped, i.e. it ignores the `Content-Encoding` header.

Here's a minimal working example:

```go
package main

import (
	"fmt"
	"net/http"

	"github.com/gorilla/handlers"
	"github.com/gorilla/mux"
	"github.com/prometheus/client_golang/prometheus/promhttp"
)

func main() {
	r := mux.NewRouter()

	r.Handle("/", promhttp.Handler())
	r.Use(handlers.CompressHandler)

	fmt.Println("Listening on :9999")
	http.ListenAndServe(":9999", r)
}
```

**Comment by elithrar** [comment]
Happy to take a PR that prevents this.

**Comment by klingtnet** [comment]
I'm on it.

**Comment by klingtnet** [comment]
Please see PR #157 for a fix.

**Comment by klingtnet** [comment]
This message is to keep the issue from being closed automatically.
