### ISSUE TITLE
CORS headers not being sent

### ISSUE THREAD

**Issue by david4shure** [gorilla/handlers#156]
I've run across a few different examples of how to configure CORS headers with gorilla muxes. This is the simplest form of that code.

```go
package main

import (
	"net/http"

	"github.com/gorilla/handlers"
	"github.com/gorilla/mux"
)

func main() {
	r := mux.NewRouter()
	r.HandleFunc("/test", Endpoint)
	corsObj := handlers.AllowedOrigins([]string{"*"})
	http.ListenAndServe(":3000", handlers.CORS(corsObj)(r))
}

func Endpoint(w http.ResponseWriter, r *http.Request) {
	w.Write([]byte("This works"))
}
```

When I run this server, and send an options request to `/test` like so

```bash
$ curl -i -XOPTIONS http://localhost:3000/test
```

I get the following curl output

```bash
HTTP/1.1 200 OK
Date: Mon, 08 Apr 2019 20:07:59 GMT
Content-Length: 0
```

The options request method is being accepted, but the server isn't responding with the Allowed origin header. I am using gorilla handlers v1.4 with Golang 1.12 using go modules on 64 bit linux. Even if I set the allowed host and allowed methods like so

```go
	corsObj := handlers.AllowedOrigins([]string{"*"})
	headers := handlers.AllowedMethods([]string{"GET", "OPTIONS"})
	http.ListenAndServe(":3000", handlers.CORS(corsObj, headers)(r))
```

It does the same thing.

**Comment by fharding1** [comment]
A couple things:

* Your first example is missing AllowedMethods, so OPTIONS isn't allowed (as you alluded to)
* Your cURL request is missing the `Origin` header.
* Your final example with `AllowedMethods` would mean you need to cURL with the `Access-Control-Request-Method` header

If I run the following example:

```go
package main

import (
        "net/http"

        "github.com/gorilla/handlers"
        "github.com/gorilla/mux"
)

func main() {
        r := mux.NewRouter()
        r.HandleFunc("/test", Endpoint)
        corsObj := handlers.AllowedOrigins([]string{"*"})
        headers := handlers.AllowedMethods([]string{"GET", "OPTIONS"})
        http.ListenAndServe(":3000", handlers.CORS(corsObj, headers)(r))
}

func Endpoint(w http.ResponseWriter, r *http.Request) {
        w.Write([]byte("This works"))
}
```

I can cURL it with:

```bash
➜  ~ curl http://localhost:3000/test -v -H "Origin: http://localhost" -H "Access-Control-Request-Method: GET" -X OPTIONS
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 3000 (#0)
> OPTIONS /test HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.64.0
> Accept: */*
> Origin: http://localhost
> Access-Control-Request-Method: GET
> 
< HTTP/1.1 200 OK
< Access-Control-Allow-Origin: *
< Date: Mon, 27 May 2019 20:30:20 GMT
< Content-Length: 0
< 
* Connection #0 to host localhost left intact
````

**Comment by elithrar** [comment]
Timing out - please let us know if you have any outstanding questions, though!

**Comment by ramswish** [comment]
but why in 200OK it is not responding with Access-Control-Request-Method hader ?

**Comment by skrater** [comment]
The Origin header is OPTIONAL for user agent, assuming the request is wrong by not having the ORIGIN header, is a bug.

More info here, at section 7.3:
https://tools.ietf.org/html/rfc6454#section-7
