### ISSUE TITLE
[bug] CORSOption MaxAge cant set more than 600 (10 minutes)

### ISSUE THREAD

**Issue by ramswish** [gorilla/handlers#170]
CORSOption MaxAge can not set more than 600 (10 minutes). it is hard coding 10 minutes if it is more than 10 mins. 

there is no limit as such in specification. even 86400 is also should be possible. i hope this should be treated as bug/enchancement. 

…

**Versions**
> Go version: go version go1.12.5 linux/amd64
> package version: 8a3748addc242fc560bd6d4ff28b0374c010b1b4

**Code Snippets**

`func MaxAge(age int) CORSOption {
	return func(ch *cors) error {
		// Maximum of 10 minutes.
		if age > 600 {
			age = 600
		}

		ch.maxAge = age
		return nil
	}
}`

…

**Comment by elithrar** [comment]
For a long time, this was capped to 10 minutes in Chromium:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Max-Age

(When this code was authored)

The challenge is that we don’t want to allow developers to set values that
aren’t reflective of reality - developers who do can easily set their own
headers.

Happy to allow a max of 86400 (Firefox) and document the browser limits in
the godoc.

**Comment by ramswish** [comment]
I totally agree w.r.t browsers. But when i implement server using handlers. then my server must support Firefox as well that means if we configure 86400 then it must support. 

cors handles giving very good framework such that we no need to implement any middleware to add these headers. if i try to add this header alone then i need to handle all the cases which cors handles is doing now. 

so i think its better to remove the restriction as server can support as big as 86400 value can support.
