### ISSUE TITLE
[bug] Memory leak in the CompressHandler

### ISSUE THREAD

**Issue by adanilovich** [gorilla/handlers#172]
**Describe the bug**
> A clear and concise description of what the bug is.
Hello, I noticed that CompressHandler contains some memory leaks because if CompressHandler is excluded from the router configuration - I don't see any memory leaks any longer. 

**Versions**
 >Go version: go version go1.13 linux/amd64
 Package version: 42206b15d7669e715f47f40a4545763b67ca12c0
 Arch Linux: 4.19.83-1-lts x86_64 GNU/Linux

**Steps to Reproduce**
> How can the bug be triggered?
I used my stress tool to send 200k queries in total. I was growing amount of queries from 50 rps to 200 rps and using monitor tool (smem) I  noticed that memory of service increased from 10Mb till 600Mb. If I tried again then memory grew more again.

**Expected behavior**
> What output or behaviour were you expecting instead?
CompressHandler should release the previously allocated memory.

**Code Snippets**
> A minimum viable code snippet can be useful! (use backticks to format it).
Below I'll demonstrate my test service and stress tool.

> test service
Run and stop several times to accelerate  the issue appearance e.g. 50 rps, 100 rps, 200 rps

	func main() {
		router := mux.NewRouter()
		router.HandleFunc("/smth", func(w http.ResponseWriter, r *http.Request) {
			w.WriteHeader(200)
			w.Write([]byte("some_string"))
		})

		router.Use(handlers.CompressHandler)
		err := http.ListenAndServe(":8080", router)
		if err != nil {
			fmt.Println(err)
		}
	}

> stress tool

	var url string = "http://127.0.0.1:8080/smth"
	var rps int = 50
	var total int = 100000

	var pch chan struct{}
	var wg sync.WaitGroup

	func main() {
		pch = make(chan struct{}, rps)

		for i := 0; i < total; i++ {
			pch <- struct{}{}
			wg.Add(1)
			go sendQuery()
		}
		wg.Wait()
	}

	func sendQuery() {
		defer wg.Done()
		defer func() { <-pch }()

		client := http.Client{}
		req, err := http.NewRequest("GET", url, nil)
		if err != nil {
			fmt.Printf("req:%s\n", err)
			return
		}

		req.Header.Add("Cache-control", "no-cache")
		req.Header.Add("Content-Type", "application/json")

		resp, err := client.Do(req)
		if err != nil {
			fmt.Printf("DO: %s\n", err)
			return
		}

		defer resp.Body.Close()
		io.Copy(ioutil.Discard, resp.Body)
	}

**Comment by elithrar** [comment]
How long is this running for - does Go release this memory? How are you
measuring memory usage?

A memory profile would be helpful.

**Comment by adanilovich** [comment]
It was working around 15min.
No, Golang didn't release the memory. I measured memory usage using smem(https://linux.die.net/man/8/smem).

Memory profile

Showing top 10 nodes out of 14
      flat  flat%   sum%        cum   cum%
23467.24kB 81.23% 81.23% 28377.59kB 98.23%  compress/flate.NewWriter
 4910.35kB 17.00% 98.23%  4910.35kB 17.00%  compress/flate.(*compressor).initDeflate
  512.05kB  1.77%   100%   512.05kB  1.77%  net.IP.String
         0     0%   100%  4910.35kB 17.00%  compress/flate.(*compressor).init
         0     0%   100% 28377.59kB 98.23%  compress/gzip.(*Writer).Write
         0     0%   100% 28377.59kB 98.23%  github.com/Sch/ries/vendor/github.com/gorilla/handlers.(*compressResponseWriter).Write
         0     0%   100% 28377.59kB 98.23%  github.com/Sch/ries/vendor/github.com/gorilla/handlers.CompressHandlerLevel.func1
         0     0%   100% 28377.59kB 98.23%  github.com/Sch/ries/vendor/github.com/gorilla/mux.(*Router).ServeHTTP
         0     0%   100% 28377.59kB 98.23%  main.main.func1
         0     0%   100%   512.05kB  1.77%  net.(*TCPAddr).String

*alloc_objects option
Showing top 10 nodes out of 93
      flat  flat%   sum%        cum   cum%
     52084  9.53%  9.53%      91649 16.77%  compress/flate.newHuffmanBitWriter
     42206  7.72% 17.25%      42206  7.72%  net/http.Header.Clone
     40960  7.49% 24.74%      50062  9.16%  context.WithCancel
     40217  7.36% 32.10%      40217  7.36%  net/textproto.MIMEHeader.Set
     39565  7.24% 39.34%      39565  7.24%  compress/flate.newHuffmanEncoder
     34332  6.28% 45.62%     156684 28.66%  net/http.(*conn).readRequest
     34206  6.26% 51.87%      34206  6.26%  compress/flate.(*huffmanEncoder).generate
     24582  4.50% 56.37%      69897 12.79%  net/http.readRequest
     24578  4.50% 60.87%      24578  4.50%  net/http.cloneURL
     21846  4.00% 64.86%     336741 61.60%  github.com/Sch/ries/vendor/github.com/gorilla/mux.(*Router).ServeHTTP

**Comment by g00dday** [comment]
Hey, guys! 
Any updates on this issue? ;-)
