### ISSUE TITLE
[bug] Request URL Host not set in ProxyHeaders handler

### ISSUE THREAD

**Issue by Enrico204** [gorilla/handlers#177]
When using `X-Forwarded-Host` header from a reverse proxy, the handler correctly sets `r.Host` (`r` is the `http.Request`), but leaves `r.URL.Host` unset. This causes some issues with some libraries (eg `httprouter`) which expects to do something like `r.URL.String()` to recover the original HTTP(S) request URL.

**Versions**
Go version: 1.13.4
package version: v1.4.2 (`8a3748a`)

**Steps to Reproduce**
Set up a reverse proxy which sends `X-Forwarded-Host` (such as Traefik) and try to print `r.URL.String()`. The URL that is built is missing the host part.

**Expected behavior**
The ProxyHeaders handler should set `r.URL.Host` as already does for `r.Host`

**Code Snippets**
```go
// Setup an HTTP server with Go and ProxyHeaders handler
// Assume a request like https://example.org/page
// Assume that the reverse proxy is sending headers:
// X-Forwarded-Host: example.org
// X-Forwarded-Proto: https

func pageHandler(w http.ResponseWriter, r *http.Request) {
   // Inside an handler function
   fmt.Println(r.URL.String())
   // this should print https://example.org/page
   // instead it prints https:///page
}
```

**Comment by elithrar** [comment]
Are we positive that setting r.URL.Host to the value of r.Host makes sense?

They are nearly always, but not always, the same. Copying the value could
be a mistake in those cases.

**Comment by Enrico204** [comment]
I don't see any situation when these two values are different here. Also, does it make sense that the `URL.Scheme` is taken from `X-Forwarded-Proto` and the `URL.Host` is not? Maybe `r.Host` should not be set to the value of the `X-Forwarded-Proto` header, while `URL.Host` does.

**Comment by Enrico204** [comment]
By reading the [`http.Request` documentation](https://golang.org/pkg/net/http/#Request), apparently `r.URL` is what is requested, based on the `Request-Line`, while `r.Host` is the host as requested in the `Host:` header (what "is sought" by the client).

So, in absence of reverse proxy `r.URL.Schema` and `r.URL.Host` are empty always (well, not always, for example in forward proxy they're populated, see RFC 7230), and only `r.URL.Path` and `r.URL.RawQuery` are populated, and `r.Host` is populated by the `Host:` header (eg. the host part of an URL).

In presence of reverse proxy, we should decide if we want to:
* leave `r.URL` as if there is no reverse proxy: this means ignoring all `X-Forwarded-*` headers for all `r.URL` fields setting it as if the reverse proxy is doing a client request to us (all fields empty except `Path` and `RawQuery`), and modifying only `r.Host` (eg. as if the reverse proxy has found us typing `example.org` in the URL address bar in a browser)
* populate all fields (`r.URL` and `r.Host) reading all standard `X-Forwarded-*`

These two alternatives both fixes the behavior above: in the former case, `r.URL.String()` will reply with an absolute URL (only `r.URL.Path`), in the latter case `r.URL.String()` will reply with schema, host and path. Eg for (https://example.org/path):
* former case (direct request, as if no rev proxy): `r.URL.String() == "/path"`
* latter case (full rev proxy aware): `r.URL.String() == "https://example.org/path"`

**Comment by Enrico204** [comment]
@elithrar Can I have a feedback about this?

**Comment by davidcroda** [comment]
We are experiencing this issue as well. There is an example of the undesirable behavior in the gorilla/mux package https://github.com/gorilla/mux/blob/master/mux.go#L187

This function returns a 301 redirect if the cleaned path (double / stripped, etc.) does not match the requested path. It modifies url.Path to the cleaned path and calls url.String() to set the location header. 

When this code is behind a reverse proxy which sets `X-Forwarded-Proto: https` and `X-Forwarded-Host: test.com` this results in an invalid redirect to `https:///cleaned_path/` rather then `https://test.com/cleaned_path/`.

I added another middleware to set r.URL.Host to match r.Host to work around the issue, but this seems like a bug. If someone is using the ProxyHeaders middleware they would expect the `X-Forwarded-Host` header to be respected in this situation.

**Comment by Enrico204** [comment]
I think that this issue should remain open until we can have a definitive answer (whether "it's a bug" or "it's a feature") from the maintainer

**Comment by pbnjay** [comment]
I'm having this same issue too, could really use this official fix

**Comment by Enrico204** [comment]
We're still waiting for an official answer on this issue, please don't close it

**Comment by Enrico204** [comment]
As this issue is going to be closed by the stale bot, I'll fix this (and other bugs that I will find) in this fork that I maintain: https://github.com/sapienzaapps/handlers

Feel free to do your PR there. I'll probably pick some of the current pull requests from this repository too
