### ISSUE TITLE
[question] how to add more context into logging handler

### ISSUE THREAD

**Issue by tooptoop4** [gorilla/handlers#179]
I see logs like below automatically printed (I don't know from what line of code), how to add more strings into this auto log ?

10.x.y.z - - [27/Feb/2020:14:42:28 +0000] "POST /route HTTP/1.1" 200 82

**Comment by elithrar** [comment]
These are from the LoggingHandler.

If you want to add more details, I’d recommend writing your own logging
middleware.

**Comment by SachinVarghese** [comment]
@elithrar Is it not possible to use a custom logging handler https://github.com/gorilla/handlers/blob/f08afc1876ad882db8074bcb8a4cc96107d3a5f4/logging.go#L253 for this?

**Comment by SachinVarghese** [comment]
Also, I feel it would be great if this package could export the `buildCommonLogLine` function to just append to the buffer so that its easier for use-cases like @tooptoop4 has mentioned. https://github.com/gorilla/handlers/blob/f08afc1876ad882db8074bcb8a4cc96107d3a5f4/logging.go#L154
