### ISSUE TITLE
[feature] Add a HeaderDecorator handler

### ISSUE THREAD

**Issue by andig** [gorilla/handlers#181]
**Is your feature request related to a problem? Please describe.**

For all my json APIs I need to add something like this:

```
// jsonHandler is a middleware that decorates responses with JSON and CORS headers
func jsonHandler(h http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json; charset=UTF-8")
		h.ServeHTTP(w, r)
	})
}

	api.Use(jsonHandler)
```

Instead, it would be nice to something like the above but pre-built similar to the CORS handler:

	api.Use(handlers.HeadersDecorator(
		map[string]string{
			"Content-Type": "application/json; charset=UTF-8",
		}
	))

**Describe alternatives you've considered**

Write my own every time, couldn't find anything ready-made. If would fit with the handlers package here. Happy to draft a PR is this looks interesting.

**Comment by andig** [comment]
@maintainers: I would be happy to contribute the handler if it makes sense from your perspective?

**Comment by elithrar** [comment]
Given this is so simple I think it’s best as documentation - not as part of a library.

This is especially true as the proposed API here only allows static values, without the ability to use request or response attributes.

**Comment by andig** [comment]
This was more meant to spark the discussion. You could argue that the cors handler is just as simple and that matching allowed headers before applying result headers (or invoking downstream handlers) could be baked in here is well. But I agree- in this simple form it probably doesn‘t warrant a middleware.
