### ISSUE TITLE
Gorilla website handler package endpoint returns an error

### ISSUE THREAD

**Issue by SunkPlane29** [gorilla/handlers#196]
While using the https://www.gorillatoolkit.org/pkg/handlers page there is no response, instead giving an internal error.

…

**Steps to Reproduce**
Making a request to the https://www.gorillatoolkit.org/pkg/handlers page the server gives an Internal Error message.

…

**Expected behavior**
> I should be able to see the handler package documentation

…

**Comment by elithrar** [comment]
All package documentation is at https://godoc.org/github.com/gorilla/handlers - linked from the README. 

This relates to https://github.com/gorilla/site/issues/17 - the Gorilla website may not be fixed for some time.

**Comment by SunkPlane29** [comment]
Thanks!
