### ISSUE TITLE
[question] CORSOption func returns an error?

### ISSUE THREAD

**Issue by martinsirbe** [gorilla/handlers#198]
Hi, first of all, thanks for this awesome library!!! 

Maybe this is a silly question, but anyway, going over the code, I noticed that:
```golang
type CORSOption func(*cors) error
```

However, non of the functions that return `CORSOption` actually return an error, only `return nil` statements. e.g.
```golang
// AllowedOrigins sets the allowed origins for CORS requests, as used in the
// 'Allow-Access-Control-Origin' HTTP header.
// Note: Passing in a []string{"*"} will allow any domain.
func AllowedOrigins(origins []string) CORSOption {
	return func(ch *cors) error {
		for _, v := range origins {
			if v == corsOriginMatchAll {
				ch.allowedOrigins = []string{corsOriginMatchAll}
				return nil
			}
		}

		ch.allowedOrigins = origins
		return nil
	}
}
```

Just wondering, is there a reason for this?

**Comment by elithrar** [comment]
Future-proofing :)

Consumers can also add their own CORSOption, if needed, and may want to return errors.

**Comment by martinsirbe** [comment]
Maybe I'm missing something, but `cors` is unexported concrete type, in order to add my own CORSOption, `cors` in `type CORSOption func(*cors) error` should be an interface, so that I can implement required functions. If I'm wrong, can you please provide an example of how you would implement one? :)
