### ISSUE TITLE
Proposed enhancements

### ISSUE THREAD

**Issue by the42** [gorilla/handlers#2]
CORSHandler
CacheHandler

and

GZipHandler come to mind. For the later there is an example here:
https://github.com/the42/schoolcalc/blob/master/webzapfen/webzapfen.go#L611

However, ideally, Handlers would be stackable.

**Comment by awsmsrc** [comment]
would a basic auth handler be a good addition.

It would need to take a validate function that accepts a username, password and returns an error

I have one

**Comment by elithrar** [comment]
@awsmsrc Might be worth opening a separate issue for that. If it's an existing repo that you'd like to merge in, provide the link. If it's fresh work, it helps to talk it over before committing too much time.

**Comment by kisielk** [comment]
Going to close this for now. Separate issues can be filed for individual enhancements.
