### ISSUE TITLE
[bug] CORS middleware panics when using Methods (cors.h is nil)

### ISSUE THREAD

**Issue by blixt** [gorilla/handlers#201]
**Describe the bug**
> A clear and concise description of what the bug is.

The CORS middleware seems to crash in some cases when using a `Subrouter()` router.

**Versions**

```
go version go1.15.2 darwin/amd64
```
Handlers version from `go.sum`:
```
github.com/gorilla/handlers v1.5.1 h1:9lRY6j8DEeeBT10CvO9hGW0gmky0BprnvDI5vfhUHH4=
github.com/gorilla/handlers v1.5.1/go.mod h1:t8XrUpc4KVXb7HGyJ4/cEnwQiaxrX/hz1Zv/4g96P1Q=
```

**Steps to Reproduce**
> How can the bug be triggered?

Create a `*mux.Router` and then configure it with `Methods` and `Use` the CORS middleware.

Run this to see the panic: https://play.golang.org/p/NWR5-CDMRbl

**Expected behavior**
> What output or behaviour were you expecting instead?

No panic.

**Code Snippets**
> A minimum viable code snippet can be useful! (use backticks to format it).

```go
package main

import (
	"net/http/httptest"

	"github.com/gorilla/handlers"
	"github.com/gorilla/mux"
)

func main() {
	r := mux.NewRouter()
	r.Methods("GET")
	r.Use(handlers.CORS())

	// Simulate a request to the router.
	req := httptest.NewRequest("GET", "https://www.example.com/v1/me", nil)
	w := httptest.NewRecorder()
	r.ServeHTTP(w, req)
}
```

**Comment by blixt** [comment]
This still panics.

**Comment by traetox** [comment]
can this be re-opened?  it is still happening in 1.8.0
