### ISSUE TITLE
An HTTP Basic auth user is not logged

### ISSUE THREAD

**Issue by jrwren** [gorilla/handlers#204]
**Describe the bug**
An HTTP Basic auth user is not logged.

Maybe this is a WONTFIX since HTTP Basic auth is so rarely used. Still, I volunteer to fix it if a fix would be acceptable.

…

**Versions**
go version go1.15 linux/amd64
github.com/gorilla/handlers v1.5.0 h1:4wjo3sf9azi99c8hTmyaxp9y5S+pFszsy3pP0rAw/lw=
github.com/gorilla/handlers v1.5.0/go.mod h1:t8XrUpc4KVXb7HGyJ4/cEnwQiaxrX/hz1Zv/4g96P1Q=
…

**Steps to Reproduce**
request a url with a username in it: e.g. curl -s http://user:pass@localhost:$PORT/
…

**Expected behavior**
I was expecting to see `user` in the user field of the common log.

…

**Comment by dolmen** [comment]
Please fix the title of this issue.

**Comment by ppai-plivo** [comment]
Had sent a fix (https://github.com/gorilla/handlers/pull/189) which was auto-closed from lack of review.
