### ISSUE TITLE
[feature] Configure CORS middleware to allow all headers

### ISSUE THREAD

**Issue by deliahu** [gorilla/handlers#210]
**Is your feature request related to a problem? Please describe.**

I would like the ability to configure the CORS middleware to allow all headers.

**Describe the solution you'd like**

The `handlers.AllowedHeaders()` function could support `"*"`, which would signal that all headers should be allowed. This is how `AllowedOrigins()` works, so it would look exactly the same (i.e. `handlers.AllowedOrigins([]string{"*"})`, and `handlers.AllowedHeaders([]string{"*"})`)

I'd be happy to make a pull request if this is something you'd accept.

**Comment by deliahu** [comment]
I still think this could be useful (let me know if someone thinks otherwise)

**Comment by amustaque97** [comment]
Hi @deliahu, could you please share how this is going to help?

Ideally, we should define `allowedHeaders` and that should work in all cases. Why do we need `handlers.AllowedHeaders([]string{"*"})`

**Comment by elithrar** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Headers

**Comment by DavidLarsKetch** [comment]
I was taking a look at #223 and notice a nuance in the MDN article @elithrar linked missing from the PR. Specifically the following:
> The value "*" only counts as a special wildcard value for requests without credentials... In requests with credentials, it is treated as the literal header name "*" without special semantics.

Digging into that, I also turned up a similar spec for the `Access-Control-Allow-Origin` response header ([source](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin)):
 > For requests _without credentials_, the literal value "*" can be specified as a wildcard
 
If either `AllowedOrigins([]string{"*"})` or `AllowedHeaders([]string{"*"})` is used in conjunction with `AllowCredentials`, the behavior would not conform to the above specs insofar as they'll continue to function as wildcards despite the intention for requests to contain credentials (which is what I understand `Access-Control-Allow-Credentials` headers to express). This could unintentionally expose credentials in client-side JS code.

For what it's worth, my limited understanding of other implementations of CORS middlewares elsewhere error out when attempting to use these wildcards alongside credentials to avoid misuse. I don't expect this to be particularly effective given this would require a change to [`CORS`](https://github.com/gorilla/handlers/blob/3e030244b4ba0480763356fc8ca0ade6222e2da0/cors.go#L160-L166) bubbling up the error. Instead, I imagine it's simpler to implement the spec as is - don't treat `*` as a wildcard when `AllowCredentials` configures the middleware.

I'm happy to contribute a PR addressing the problem, but curious if this checks out with you all.

**Comment by amustaque97** [comment]
> I'm happy to contribute a PR addressing the problem

@DavidLarsKetch  Would love to see PR

**Comment by kdeloach** [comment]
For what it's worth, I had a use case for this a while back.

We had a bunch of microservices which supported different headers. For simplicity, the frontend app indiscrimintantly passed all headers to each service. So when `Service A` added header `X-Foo` it would break `Service B` which had no knowledge of that header. These services were managed by different teams or else this would be a non-issue.

For us, it was more trouble than it was worth to maintain header whitelists across services. We had to create a custom middleware to fix this.

I created a PR for this a while back that got closed. https://github.com/gorilla/handlers/pull/180

**Comment by DavidLarsKetch** [comment]
#226 is up per this conversation. As far as I understand the spec, the rule around wildcards for "Access-Control-Allow-Origin" applies to "Access-Control-Allow-Headers" as well so whatever implementation gets merged in, would need to follow that.
