### ISSUE TITLE
[question] Possible to change IP in CombinedLoggingHandler?

### ISSUE THREAD

**Issue by maxsupermanhd** [gorilla/handlers#213]
I am using Cloudflare to proxy all traffic, it leaves http field of real remote IP, how can I change handler to log different fields?
Theoretically I can force-replace IP with copy from Cloudflare's header but I don't know how to do it...

**Comment by maxsupermanhd** [comment]
Can I get an answer?

**Comment by elithrar** [comment]
See https://pkg.go.dev/github.com/gorilla/handlers#ProxyHeaders - which should be added before the Logging handler.
