### ISSUE TITLE
[feature] use x-real-ip instead of client ip if possible in logginghandler

### ISSUE THREAD

**Issue by henri9813** [gorilla/handlers#216]
I use traefik as RP and all my logs just contains the ip of the TRaefik load balancer instead of the real ip.

I would like to have the possibilities to have the `x-real-ip` instead of the client ip in the logs.
…

**Describe the solution you'd like**
>What would the feature look like? How would it work? How would it change the API?
I would like the handler use the x-real-ip if available.

```
if r.Header.Get("X-Real-IP") != "" {
                clientAddress = r.Header.Get("X-Real-IP")
        }
```
…

**Describe alternatives you've considered**
> Are there alternatives you've tried, and/or workarounds in-place?

…
Maybe another handler ? or a parameter ?

**Comment by Vivalldi** [comment]
If use `handlers.ProxyHeaders` before `handlers.LoggingHandler` it _should_ replace `RemoteAddr` before the logger is reads it

**Comment by henri9813** [comment]
Oh, the name of the handler should be: "ProxyHeadersHandler" no ? 

This is disturbing

**Comment by Vivalldi** [comment]
Maybe? Though `CORS` isn't `CORSHandler` so I'll leave that to the `gorilla` team to decice

**Comment by elithrar** [comment]
We can’t rename the functions without breaking the API, and I’m not sure a
duplicate function with a similar name is better / less confusing now.
