### ISSUE TITLE
[feature] FileServer handler

### ISSUE THREAD

**Issue by cirelli94** [gorilla/handlers#219]
**Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is - e.g. "I'm always frustrated when [...]"

I'd like to have an handler like [http.FileServer](https://pkg.go.dev/net/http#FileServer) that is able to return only files metadata in json format, instead of an html page, if the `Accept` header `application/json` is used.

The problem has already been well discussed in several issues in other projects:
https://github.com/golang/go/issues/23898
https://github.com/jasonwbarnett/go/issues/1

**Describe the solution you'd like**
>What would the feature look like? How would it work? How would it change the API?

In this issue I'd like to understand if it would be good to add this handler in this library.
There is already a solution implemented from @jasonwbarnett : https://github.com/jasonwbarnett/fileserver
The original http.FileServer is wrapped by a check of the `Accept` header, and if it's `application/json` it returns only metadata of files of the path requested in json format.

**Describe alternatives you've considered**
> Are there alternatives you've tried, and/or workarounds in-place?

Use directly https://github.com/jasonwbarnett/fileserver , or fork it and maintain it by myself.

**Comment by amustaque97** [comment]
Hi @cirelli94, apologise for the late reply. I'm guessing your work must be done by now.  I want to explain here that though this project name is `handler` we add/maintain middleware that works with every request/response. Working on something like `fileserver` is an individual route specific thus doesn't fit this project purpose. I hope I'm able to explain my concerns. 


cc @elithrar , please go through the above comment. If you also agree then we can close this issue.

**Comment by cirelli94** [comment]
I understood and I agree with you, don't worry!
Thank you for the answer.
