### ISSUE TITLE
[feature] add brotli encoding support in compress handler 

### ISSUE THREAD

**Issue by morlay** [gorilla/handlers#220]
**Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is - e.g. "I'm always frustrated when [...]"

For modern browsers, brotli is widely supported.
https://caniuse.com/?search=brotli

It could add brotli encoding support in Compress handler

**Describe the solution you'd like**
>What would the feature look like? How would it work? How would it change the API?

here a pure go pkg github.com/andybalholm/brotli

**Describe alternatives you've considered**
> Are there alternatives you've tried, and/or workarounds in-place?

If don't want to add a vendor deps here.
Conside added options to register encoding and its Writer

**Comment by amustaque97** [comment]
I believe it's a good feature to have. Will be happy to see PR submissions. Or will have to wait for sometime to expect a PR from my side.

**Comment by DavidLarsKetch** [comment]
> If don't want to add a vendor deps here.
> Conside added options to register encoding and its Writer

While the Go core team has different, more complicated concerns then us, it is important to note that a recent proposal to add a `compress/brotli` package was retracted [here](https://github.com/golang/go/issues/42967), so there is no timeline for a std lib package providing the compression we'd need for this feature.

Adding an option to bring your own encoder/`io.Writer` would also push mapping which values in the `Accept-Encoding` header entail calling this custom encoder. The signatures of `CompressHandler` and `CompressHandlerLevel` ought not change without a major version bump, so I'm not seeing a clean path here.
