### ISSUE TITLE
[question] upgrade httpsnoop

### ISSUE THREAD

**Issue by malt3** [gorilla/handlers#234]
**Describe the problem you're having**

I am using multiple dependencies, some using github.com/felixge/httpsnoop@v1.0.3.
Would it be possible to upgrade httpsnoop to 1.0.3? As far as I can tell, there are no breaking changes.
…

**Versions**
> Go version: go version go1.19 linux/amd64

> package version: 3e030244b4ba0480763356fc8ca0ade6222e2da0

…

**"Show me the code!"**

```shell-session
go work sync
go: version constraints conflict:
	github.com/honeycombio/beeline-go@v1.1.1 requires github.com/felixge/httpsnoop@v1.0.3, but github.com/felixge/httpsnoop@v1.0.1 is requested
	github.com/letsencrypt/boulder@v0.0.0-20220331220046-b23ab962616e requires github.com/felixge/httpsnoop@v1.0.3, but github.com/felixge/httpsnoop@v1.0.1 is requested
	github.com/sigstore/sigstore@v1.3.0 requires github.com/felixge/httpsnoop@v1.0.3, but github.com/felixge/httpsnoop@v1.0.1 is requested
```
…

**"Possible solution"**

Upgrade httpsnoop using `go get -u github.com/felixge/httpsnoop`.

**Comment by coreydaley** [comment]
Completed via https://github.com/gorilla/handlers/pull/241
