### ISSUE TITLE
is this compatible with alice

### ISSUE THREAD

**Issue by alioygur** [gorilla/handlers#29]
hi gorilla team,

i am using [justinas/alice](https://github.com/justinas/alice) for chaning handlers. (middleware)

i want use **LoggingHandler** that handler of "gorilla/handlers"  package, but i can not do it. is this compatible with that ?

**Comment by elithrar** [comment]
Sure is. Both satisfy the `http.Handler` interface - e.g.

```go
package main

import (
	"fmt"
	"net/http"
	"os"

	"github.com/gorilla/handlers"
)

func SomeHandler(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintln(w, "Hello!")
}

func main() {
	r := http.DefaultServeMux
	// Note that because LoggingHandler is a http.Handler, and accepts a http.Handler,
	// you need to use mux.Handle and type cast your handlers explicitly.
	r.Handle("/", handlers.LoggingHandler(os.Stdout, http.HandlerFunc(SomeHandler)))

	http.ListenAndServe(":8000", nil)
}

```

Output of `curl http://localhost:8000`

```
~/Desktop go run alice_logger.go
::1 - - [22/Apr/2015:05:26:52 +0800] "GET / HTTP/1.1" 200 7
```

If this isn't what you're trying to achieve, post some example code. Without it I'm just guessing :)

**Comment by alioygur** [comment]
@elithrar thank you for your answer, but my problem is, i want use that with justinas/alice

imagine that you have 50+ route so i repeat yourself. like

```
r.Handle("/", handlers.LoggingHandler(os.Stdout, http.HandlerFunc(SomeHandler)))
r.Handle("/xpage", handlers.LoggingHandler(os.Stdout, http.HandlerFunc(XPageHandler)))
r.Handle("/ypage", handlers.LoggingHandler(os.Stdout, http.HandlerFunc(YPageHandler)))
...
```

the alice package able to chain handler. can you show me an example with alice

**Comment by elithrar** [comment]
Whoops, forgot that part. It will still work - can you show me what you've
tried? I won't be in front of a PC for another hour.

**Comment by alioygur** [comment]
please wait about 2 minutes

**Comment by alioygur** [comment]
```
package main

import (
	"github.com/gorilla/handlers"
	"github.com/justinas/alice"
	"net/http"
)

func HomeHandler(rw http.ResponseWriter, req *http.Request) {
	rw.Write([]byte("home"))
}

func ContactPageHandler(rw http.ResponseWriter, req *http.Request) {
	rw.Write([]byte("contact page"))
}

func AboutPageHandler(rw http.ResponseWriter, req *http.Request) {
	rw.Write([]byte("about page"))
}

func main() {

    // right there is a problem! ???
	CommonMiddlewareStack := alice.New(handlers.LoggingHandler)

	http.Handle("/", CommonMiddlewareStack.ThenFunc(HomeHandler))
	http.Handle("/contact", CommonMiddlewareStack.ThenFunc(ContactPageHandler))
	http.Handle("/about", CommonMiddlewareStack.ThenFunc(AboutPageHandler))

	http.ListenAndServe(":8000", nil)
}
```

when i run, i get this error

```
➜  webapp  go run main.go 
# command-line-arguments
./main.go:23: cannot use handlers.LoggingHandler (type func(io.Writer, http.Handler) http.Handler) as type alice.Constructor in function argument
```

**Comment by kisielk** [comment]
Did you read the documentation for alice?

"""
Your middleware constructors should have the form of

    func (http.Handler) http.Handler

Some middleware provide this out of the box. For ones that don't, it's trivial to write one yourself.

    func myStripPrefix(h http.Handler) http.Handler {
        return http.StripPrefix("/old", h)
    }
"""

So you need a thin wrapper over the `handles.Logging` handler function to make it conform to the interface alice expects. Something like:

```
func myLoggingHandler(h http.Handler) http.Handler {
    return handlers.LoggingHandler(os.Stderr, h)
}

func main() {
    // right there is a problem! ???
    CommonMiddlewareStack := alice.New(myLoggingHandler)
    ....
```

**Comment by alioygur** [comment]
ohhh thank you man.
