### ISSUE TITLE
hijackLogger/responseLogger doesn't support http.Flusher interface

### ISSUE THREAD

**Issue by yichengq** [gorilla/handlers#34]
I want this because we use streaming in handlers that wrapped by LoggingHandler.

I have seen the discussion on #24 . There are possible two solutions so far:
1. implement Flush() for responseLogger. But it may have side effect.
2. expose a function to return the raw writer, so I can use it directly.

I can send a PR if you think the solution is good.

related: https://github.com/coreos/discovery.etcd.io/issues/32

**Comment by kisielk** [comment]
Support for `Flush` etc. was added in 88457b67c1a
