### ISSUE TITLE
Cannot change req.URL.User 

### ISSUE THREAD

**Issue by vetinari** [gorilla/handlers#39]
The req.URL.User cannot be changed after the logging handler started. To keep the req.URL "read only", the following change would be great:
```
 diff --git a/handlers.go b/handlers.go
 index 23a738d..6a58644 100644
 --- a/handlers.go
 +++ b/handlers.go
 @@ -73,6 +73,9 @@ func (h loggingHandler) ServeHTTP(w http.ResponseWriter, req *http.Request) {
         }
         url := *req.URL
         h.handler.ServeHTTP(logger, req)
 +       if req.URL.User != nil {
 +               url.User = req.URL.User
 +       }
         writeLog(h.writer, req, url, t, logger.Status(), logger.Size())
  }
 
 @@ -86,6 +89,9 @@ func (h combinedLoggingHandler) ServeHTTP(w http.ResponseWriter, req *http.Reque
         }
         url := *req.URL
         h.handler.ServeHTTP(logger, req)
 +       if req.URL.User != nil {
 +               url.User = req.URL.User
 +       }
         writeCombinedLog(h.writer, req, url, t, logger.Status(), logger.Size())
  }
 
```
Let me know if you want a PR for that.

**Comment by kisielk** [comment]
Why would the handler modify the request user, and why wouldn't you want to log the user of the original request?

**Comment by vetinari** [comment]
When the authentication is done with OAuth2 there is no username associated with the request before the authentication was done (and succeeded), the Authorization header looks like
```Authorization: Bearer 1dd4b9fc-2b6b-4ac6-9bb5-XXXXXXXXXXXX```
The logging handler must run before the authentication handler, otherwise I would not get a failed request in the logs.

**Comment by kisielk** [comment]
Hm, what are you using that modifies the `req.URL.User` to have the oath2 user? That doesn't seem like the normal place to put that kind of thing, I'd expect it to be in some sort of context like `gorilla/context` or `net/context`. `URL.User` is intended to represent the user portion of a URL, eg: http://[user]@domain and that's what's being logged here. 

I guess what I'm getting at is the purpose of this handler is to log HTTP requests in a manner similar to what the Apache common log format contains. Getting in to the details of how particular packages handle authentication after the fact seems to be beyond the scope, so I'm a bit reluctant to begin down that path.

**Comment by kisielk** [comment]
Thought about this some more and I still don't really feel good about adding it. What if the handler chain also changes other parts of the URL, such as the query, etc. Should we also log those after they've been changed by the handlers? It feels weird to special-case just user for this. Perhaps there should be an option to get req.URL before or after the handlers fire?

**Comment by elithrar** [comment]
I think this is definitely a case where a request context (either gorilla/context or net/context) is better suited.

**Comment by kisielk** [comment]
Definitely as far as passing the user down goes I think that's a better solution. I guess it would just require a different kind of logging handler than this one.
