### ISSUE TITLE
CORSHandler: returns Method not allowed for OPTIONS

### ISSUE THREAD

**Issue by krishnasrinivas** [gorilla/handlers#68]
For OPTIONS request the CORS middleware passes the request to the next middleware which always returns '405' status.

this fixes it:
```go
@@ -112,6 +114,10 @@ func (ch *cors) ServeHTTP(w http.ResponseWriter, r *http.Request) {
 
        w.Header().Set(corsAllowOriginHeader, origin)
 
+       if r.Method == corsOptionMethod {
+               return
+       }
+
        ch.h.ServeHTTP(w, r)
 }
 
```

Is this a bug or am I doing something wrong?

**Comment by elithrar** [comment]
Can you show me your code as well?

**Comment by dautushenka** [comment]
I agree with Krishna
Options requests should not be passed to next handler.
We should add condition like this
https://github.com/gorilla/handlers/pull/71

**Comment by krishnasrinivas** [comment]
@elithrar Sorry I had forgotten about this issue! using [this](https://github.com/rs/cors) package now, you can close the issue if you think the code is fine. Maybe there was some issue with my code. But if @dautushenka is also facing an issue you can look at it.

**Comment by elithrar** [comment]
If you can address my comment in https://github.com/gorilla/handlers/pull/71 we
can merge it :)

**Comment by elithrar** [comment]
Closed via https://github.com/gorilla/handlers/pull/71 - thanks @dautushenka.
