### ISSUE TITLE
Do a repository release

### ISSUE THREAD

**Issue by apremalal** [gorilla/handlers#69]
Go dependency management tools like [Gom](https://github.com/mattn/gom) use a particular commitid/ tag to checkout the dependencies. Since this repo doesn't have a tag users have to stick to commitids, which is not clean and hard to track.

**Comment by elithrar** [comment]
@apremalal https://github.com/gorilla/handlers/releases/tag/v1.1 :)

**Comment by apremalal** [comment]
@elithrar Thanks for making this :)
