### ISSUE TITLE
Tag another release

### ISSUE THREAD

**Issue by aaronkavlie-wf** [gorilla/handlers#76]
v1.1 was done in February, and is missing some important functionality (at least in the CORS handler).

**Comment by elithrar** [comment]
I'll look to tag another release shortly. Note that master is stable, so you can safely pull from master. Your CI should be able run tests and check for any breakage.

**Comment by aaronkavlie-wf** [comment]
We updated to latest master, but we're trying to specify version numbers for projects that have them.

**Comment by dsansotscea** [comment]
:+1: Us too (pulling from master), but would love to specify a release version.

**Comment by joefitzgerald** [comment]
Please make another release, and continue this practice. Many thanks!

**Comment by elithrar** [comment]
https://github.com/gorilla/handlers/releases/tag/v1.2
