### ISSUE TITLE
Cache Control & Static File Server

### ISSUE THREAD

**Issue by wayneashleyberry** [gorilla/handlers#81]
Hi Gorilla Team :) Firstly thank you for all of the great packages!

I've been struggling to find a package that has sensible cache control headers for static files. Would something like that be a useful handler? My first thought was that it would feel right living next to the logging and compression handlers.

There are pretty sensible defaults located at [github.com/h5bp/server-configs-nginx](https://github.com/h5bp/server-configs-nginx/blob/3f4719b79abd510a07e8a5635b85a53077480237/h5bp/location/expires.conf)

Example:

``` go
package main

import (
    "fmt"
    "net/http"
    "os"

    "github.com/gorilla/mux"
)

func main() {
    r := mux.NewRouter()
    r.HandleFunc("/", HomeHandler)
    r.PathPrefix("/").Handler(handlers.StaticCache(http.FileServer(http.Dir("./static/"))))
    http.ListenAndServe(os.Getenv("HOST")+":"+os.Getenv("PORT"), r)
}

func HomeHandler(w http.ResponseWriter, r *http.Request) {
    fmt.Fprintf(w, "Hello, World")
}

```

**Comment by elithrar** [comment]
Sure, there's definitely interest. Something that sniffs MIME types (ala nginx) would be best.

**Comment by wayneashleyberry** [comment]
I'm pretty new to Go, but would this approach make sense? Basing the expiration on the extension might not be the best but I couldn't find how get get file / mime types.

```go
func MaxAge(h http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		var age time.Duration
		ext := filepath.Ext(r.URL.String())

		// Timings are based on h5bp/server-configs-nginx
		// https://github.com/h5bp/server-configs-nginx/blob/master/h5bp/location/expires.conf

		switch ext {
		case ".rss", ".atom":
			age = time.Hour / time.Second
		case ".css", ".js":
			age = (time.Hour * 24 * 365) / time.Second
		case ".jpg", ".jpeg", ".gif", ".png", ".ico", ".cur", ".gz", ".svg", ".svgz", ".mp4", ".ogg", ".ogv", ".webm", ".htc":
			age = (time.Hour * 24 * 30) / time.Second
		default:
			age = 0
		}

		if age > 0 {
			w.Header().Add("Cache-Control", fmt.Sprintf("max-age=%d, public, must-revalidate, proxy-revalidate", age))
		}

		h.ServeHTTP(w, r)
	})
}
```

**Comment by wayneashleyberry** [comment]
I'm also not sure about the `public, must-revalidate, proxy-revalidate` options, I got that from this discussion: https://groups.google.com/forum/#!topic/golang-nuts/n-GjwsDlRco

**Comment by wayneashleyberry** [comment]
https://github.com/gorilla/handlers/pull/82
