### ISSUE TITLE
Using handler.CompressHandler with mux.NotFoundHandler

### ISSUE THREAD

**Issue by wayneashleyberry** [gorilla/handlers#83]
Hey,

I seem to be getting errors when using a `CompressHandler` in conjunction with a `NotFoundHandler`. In the following example my 404's don't work at all and the browser's just dumping a "This site can’t be reached" error to the screen. No error messages or stack traces coming from Go either :/

If I comment out `r.NotFoundHandler` or `h2 := handlers.CompressHandler(h1)` then it works.

``` go
package main

import (
    "fmt"
    "net/http"
    "os"

    "github.com/gorilla/handlers"
    "github.com/gorilla/mux"
)

func main() {
    r := mux.NewRouter()

    r.HandleFunc("/", IndexHandler).Methods("GET")
    r.HandleFunc("/test", TestHandler).Methods("GET")
    r.NotFoundHandler = http.HandlerFunc(NotFoundHandler)

    h1 := handlers.CombinedLoggingHandler(os.Stdout, r)
    h2 := handlers.CompressHandler(h1)

    http.ListenAndServe("localhost:"+os.Getenv("PORT"), h2)
}

func NotFoundHandler(w http.ResponseWriter, r *http.Request) {
    w.WriteHeader(http.StatusNotFound)
    fmt.Fprintf(w, "404 - Not Found")
}

func IndexHandler(w http.ResponseWriter, r *http.Request) {
    fmt.Fprintf(w, "Hello, World!")
}

func TestHandler(w http.ResponseWriter, r *http.Request) {
    fmt.Fprintf(w, "Looks good!")
}
```

**Comment by wayneashleyberry** [comment]
Looks like the call to `w.WriteHeader()` is causing the problem, but without it my 404 pages have a 200 status code.

**Comment by elithrar** [comment]
Interesting. Go 1.7?

**Comment by wayneashleyberry** [comment]
Yup, 1.7

**Comment by wayneashleyberry** [comment]
Yeah, this is very strange. I've just found if I leave the browser error open for a while I get asked if I want to allow the site to download multiple files... but nothing actually downloads.

Here's what curl gets:

```
~sh
🍡  curl -X GET http://localhost:3000/foo -v
*   Trying ::1...
* Connected to localhost (::1) port 3000 (#0)
> GET /foo HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Content-Type: application/x-gzip
< Date: Mon, 05 Sep 2016 07:30:15 GMT
< Vary: Accept-Encoding
< Content-Length: 15
<
* Connection #0 to host localhost left intact
404 - Not Found
```

**Comment by wayneashleyberry** [comment]
Looks like [compress.go#L25](https://github.com/gorilla/handlers/blob/a5775781a543af3c6b9f5baf10995e4d14168950/compress.go#L25) is the problem, commenting it out fixes this issue.

**Comment by wayneashleyberry** [comment]
Hey @jehiah, I see you added a lot of tests for the compress handler - do you perhaps have some insight into this?

**Comment by elithrar** [comment]
@wayneashleyberry The gzip middleware writes the header as it's own `WriteHeader` implementation deletes the `Content-Length` header, so it still needs to write the header the caller (application) requested.

If you comment that out, are you seeing the correct status codes written in all cases (e.g. non-200's)?

This should not have changed under Go 1.7, either.

**Comment by wayneashleyberry** [comment]
Ah no, if I comment out `w.ResponseWriter.WriteHeader(c)` then my 404's return 200 :(

**Comment by wayneashleyberry** [comment]
I'm actually running into the same issue using https://github.com/phyber/negroni-gzip instead.

**Comment by elithrar** [comment]
I suspect that https://github.com/NYTimes/gziphandler won't cause the issue
- I'd be curious if go install -gcflags=-ssa=0 worked as well, though.

**Comment by wayneashleyberry** [comment]
Looks like I'm getting the exact same issue with the NYTimes/gziphandler, this is bleak :/

**Comment by wayneashleyberry** [comment]
Might be related to https://github.com/NYTimes/gziphandler/issues/5?

**Comment by elithrar** [comment]
And with SSA disabled?

**Comment by wayneashleyberry** [comment]
Not quite sure where I run that command @elithrar, I tried running it in `$GOPATH/src/github.com/wayneashleyberry/go-website` and then ran `go build` again but got the same issue.

**Comment by wayneashleyberry** [comment]
While checking out the source for `http.Error` I think I might've found something. For some reason, setting the content type header makes this problem go away.

https://golang.org/src/net/http/server.go?s=51433:51485#L1725

```go
package main

import (
	"fmt"
	"net/http"
	"os"
	"path"

	"github.com/gorilla/handlers"
	"github.com/gorilla/mux"
)

func main() {
	r := mux.NewRouter()
	r.NotFoundHandler = http.HandlerFunc(NotFoundHandler)
	r.HandleFunc("/", HomeHandler)
	gzip := handlers.CompressHandler(r)
	http.ListenAndServe(":"+os.Getenv("PORT"), gzip)
}

func NotFoundHandler(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	w.WriteHeader(http.StatusNotFound)
	fmt.Fprintf(w, "404 - not found")
}

func HomeHandler(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello, World!")
}
```

**Comment by wayneashleyberry** [comment]
While checking out the source for `http.Error` I think I might've found something. For some reason, setting the content type header makes this problem go away.

https://golang.org/src/net/http/server.go?s=51433:51485#L1725

```go
package main

import (
	"fmt"
	"net/http"
	"os"
	"path"

	"github.com/gorilla/handlers"
	"github.com/gorilla/mux"
)

func main() {
	r := mux.NewRouter()
	r.NotFoundHandler = http.HandlerFunc(NotFoundHandler)
	r.HandleFunc("/", HomeHandler)
	gzip := handlers.CompressHandler(r)
	http.ListenAndServe(":"+os.Getenv("PORT"), gzip)
}

func NotFoundHandler(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	w.WriteHeader(http.StatusNotFound)
	fmt.Fprintf(w, "404 - not found")
}

func HomeHandler(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello, World!")
}
```

**Comment by wayneashleyberry** [comment]
Setting the content-type header prevents the same thing from happening when using `github.com/NYTimes/gziphandler` so I'm gonna assume it'll work for the negroni middlewares as well. Although it works I'd love to know why and if this should even be considered a "fix".

**Comment by elithrar** [comment]
Without a Content-Type the browser doesn't know what to do. We should either:

* Document the requirement for Content-Type
* Set it as a last-resort ourselves.

Would you be able to PR this?

**Comment by jehiah** [comment]
@elithrar I think i can add some context here. For debugging `curl --compressed -v ...` is helpful.

Typically if `Content-Type` is omitted it's guessed by `http.Server`. quoting [`http.ResponseWriter.Write`](https://golang.org/pkg/net/http/#ResponseWriter)

> If WriteHeader has not yet been called, Write calls
> WriteHeader(http.StatusOK) before writing the data. If the Header
> does not contain a Content-Type line, Write adds a Content-Type set
> to the result of passing the initial 512 bytes of written data to
> DetectContentType.


What is important is to make sure that `Write()` from `http.Server` is not guessing the content type as `application/octet-stream` which happens when the first 512 bytes are compressed. To avoid that `handler.CompressHandler.Write` also has content type detection logic so it's based on uncompressed content.

Unfortunately the docs for [`http.ResponseWriter.Write`](https://golang.org/pkg/net/http/#ResponseWriter) have an important context...

> Changing the header after a call to WriteHeader (or Write) has no effect ...

So. `handler.CompressHandler.Write` can no longer modify headers after `WriteHeader()` is called  because that flushes the headers of the request. This means that in non-200 code responses or any time WriteHeader is called before Write we should 

a) skip compression
b) skip compression if we don't already have a content-type set
c) document/require a content-type must be set.

So if you put these things together, given the example from @wayneashleyberry you get `Content-Type: application/octet-stream`

```
curl -v --compressed 'http://127.0.0.1:8081/tess'
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 8081 (#0)
> GET /tess HTTP/1.1
> Host: 127.0.0.1:8081
> User-Agent: curl/7.43.0
> Accept: */*
> Accept-Encoding: deflate, gzip
> 
< HTTP/1.1 404 Not Found
< Content-Encoding: deflate
< Vary: Accept-Encoding
< Date: Sun, 18 Sep 2016 19:49:42 GMT
< Content-Length: 21
< Content-Type: application/octet-stream
< 
* Connection #0 to host 127.0.0.1 left intact
404 - Not Found
```

**Comment by elithrar** [comment]
Correct.

We need to effectively replicate wroteHeader in the default ResponseWriter
implementation - https://golang.org/src/net/http/server.go?s=2530:4338#L878 -
so that we can determine whether WriteHeader was called or not, and be more
intelligent around that.
