### ISSUE TITLE
can't find import: "github.com/gorilla/context"

### ISSUE THREAD

**Issue by wayneashleyberry** [gorilla/handlers#85]
I'm trying to deploy an app to appengine, which used to work fine, all of a sudden I'm getting this error message. Not sure if it's an issue with app engine, my code, gorilla/handlers or go...

source is here: https://github.com/wayneashleyberry/wayneashleyberry.com

```sh
❯ gcloud app deploy
You are about to deploy the following services:
 - wayneashleyberry-com/default/20160912t185450 (from [/Users/Wayne/src/github.com/wayneashleyberry/wayneashleyberry.com/app.yaml])
     Deployed URL: [https://wayneashleyberry-com.appspot.com]

Do you want to continue (Y/n)?  y

Beginning deployment of service [default]...
WARNING: Some files were skipped. Check the gcloud log file or pass `--verbosity=info` to see which ones.
File upload done.
Updating service [default]...failed.
ERROR: (gcloud.app.deploy) Error Response: [9] Deployment contains files that cannot be compiled: Compile failed:
2016/09/12 09:55:04 go-app-builder: build timing: 1×compile (103ms total), 0×link (0 total)
2016/09/12 09:55:04 go-app-builder: failed running compile: exit status 1

website/website.go:8: can't find import: "github.com/gorilla/handlers"
```

**Comment by wayneashleyberry** [comment]
It might be worth noting, I'm using 1.7.1 locally and do indeed have all of those dependencies installed via `go get`. I've also tried vendoring them to no avail.

**Comment by wayneashleyberry** [comment]
Just tried in a clean workspace using 1.6.3 and got the same issue.

**Comment by wayneashleyberry** [comment]
my bad, was deploying with the wrong sdk :/

**Comment by dkanas** [comment]
Can you say more on that, @wayneashleyberry, please? Having the same problem, but i don't know how to solve it.

**Comment by elithrar** [comment]
Make sure you are using Go 1.7 or newer on app engine itself.

**Comment by adityavarma1234** [comment]
My version is 1.9 but it is still not working. 

`2017/09/25 20:40:19 failed analyzing /home/aditya/Documents/work/helloworld: cannot find package "github.com/gorilla/context" `

**Comment by juancaacuna** [comment]
Just do:
```bash
go get github.com/gorilla/context
```

**Comment by adityavarma1234** [comment]
Thanks. I had to use -u option and there was some issue in the path.
