### ISSUE TITLE
Add request time for logs

### ISSUE THREAD

**Issue by hekaldama** [gorilla/handlers#88]
Would it be possible to have request time on the log output like:

http://nginx.org/en/docs/http/ngx_http_log_module.html#var_request_time

**Comment by elithrar** [comment]
I don't believe request duration is part of the Apache Common Log Format - https://httpd.apache.org/docs/1.3/logs.html#common - unless I've missed something?

**Comment by hekaldama** [comment]
You are totally correct but wanted to see if it would be possible to add as an option for people to take advantage of. I don't really have any clear design for the interface for accessing this option, but I am happy to discuss and possibly PR if helpful / desired.

Thanks.

**Comment by elithrar** [comment]
We'd need to support a different logger, and if that's a requirement I
think there's enough logging libs out there that can do that.
gorilla/handlers is intentionally simple/generalized.

You can copy the code in
https://gist.github.com/elithrar/887d162dfd0c539b700ab4049c76e22b if you
want something else ;)

**Comment by hekaldama** [comment]
Okay. Thanks for the replies.
