### ISSUE TITLE
Logging Handlers and Recovery handlers do not support structured JSON output

### ISSUE THREAD

**Issue by pavelnikolov** [gorilla/handlers#91]
My team manages hundreds of micro services on thousands on nodes. We monitor everything and send our logs to a centralized logging solution, where we can query and analyze the logs.
The apache log format used by the `LoggingHandler` might be fine for most use cases but is definitely no ok for our case. That is why I would really appreciate it if there was a `JSONLoggingHandler` or `StructuredLoggingHandler`, which logs the same information but as a single-line JSON document. This would allow me to easily query the data without having to parse the logs and convert them to JSON.

**Comment by elithrar** [comment]
I would strongly suggest using https://github.com/go-kit/kit/tree/master/log
in that case, rather than extending this library. I'm not sure what the
benefit to reinventing the wheel here is (each library has its pros/cons).

**Comment by elithrar** [comment]
Closing.
