### ISSUE TITLE
Access-Control-Expose-Headers not added to preflight

### ISSUE THREAD

**Issue by cmoad** [gorilla/handlers#99]
The `Access-Control-Expose-Headers` header is added to the GET request (or any non-OPTIONS request) following a preflight, but it is excluded from the preflight. I wasn't able to find hard documentation stating where this header should go, but I can attest that I can't access a custom header in JavaScript unless I also add the `Access-Control-Expose-Headers` header to the preflight response in the latest Chrome.

https://github.com/gorilla/handlers/blob/master/cors.go#L100

**Comment by cmoad** [comment]
After more testing, this must have been another issue. I am able to confirm v1.2.0 is working as expected.

**Comment by elithrar** [comment]
Thank you for reporting back!

**Comment by cmoad** [comment]
Thank you for the project!
